version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: carpool_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  app:
    build: .
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: carpool_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      JWT_SECRET: change_this_in_production
      JWT_EXPIRE: 7d
      CORS_ORIGIN: "*"
    depends_on:
      - db
    command: sh -c "sleep 5 && node server/index.js"

volumes:
  postgres_data:
